#!/bin/bash

# Quick Deployment Commands Reference
# Vercel (Frontend) + Render (Backend) + Neon (Database)

echo "🚀 HRMS Quick Deployment Commands"
echo "=================================="
echo ""

# Database Setup (Neon)
echo "📊 1. DATABASE SETUP (Neon)"
echo "   → Create database at: https://neon.tech"
echo "   → Get connection string"
echo "   → Run migrations locally:"
echo ""
echo "   cd backend"
echo "   # Update .env with Neon credentials"
echo "   npm install"
echo "   npm run migrate"
echo "   npm run seed"
echo ""

# Git Setup
echo "📦 2. GIT SETUP"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Ready for deployment'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

# Render (Backend)
echo "🔧 3. BACKEND DEPLOYMENT (Render)"
echo "   → Go to: https://dashboard.render.com"
echo "   → New + → Web Service"
echo "   → Connect GitHub repo"
echo "   → Settings:"
echo "     - Root Directory: backend"
echo "     - Build Command: npm install"
echo "     - Start Command: npm start"
echo "   → Add Environment Variables:"
echo "     NODE_ENV=production"
echo "     PORT=10000"
echo "     JWT_SECRET=<generate-with: openssl rand -hex 32>"
echo "     DB_HOST=<neon-host>"
echo "     DB_PORT=5432"
echo "     DB_NAME=<neon-db>"
echo "     DB_USER=<neon-user>"
echo "     DB_PASSWORD=<neon-password>"
echo "     FRONTEND_URL=<vercel-url>"
echo ""

# Vercel (Frontend) - CLI
echo "🎨 4. FRONTEND DEPLOYMENT (Vercel)"
echo ""
echo "   Option A: Via CLI"
echo "   npm install -g vercel"
echo "   cd staff-verse"
echo "   vercel login"
echo "   vercel"
echo "   vercel env add VITE_API_URL production"
echo "   # Enter: https://your-backend.onrender.com/api"
echo "   vercel --prod"
echo ""
echo "   Option B: Via Dashboard"
echo "   → Go to: https://vercel.com"
echo "   → Add New → Project"
echo "   → Import GitHub repo"
echo "   → Settings:"
echo "     - Framework: Vite"
echo "     - Root Directory: staff-verse"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "   → Add Environment Variable:"
echo "     VITE_API_URL=https://your-backend.onrender.com/api"
echo ""

# Testing
echo "✅ 5. TEST DEPLOYMENT"
echo "   curl https://your-backend.onrender.com/api/health"
echo "   # Should return: {\"status\":\"OK\",...}"
echo "   # Visit frontend URL and login with:"
echo "   # Username: admin"
echo "   # Password: admin123"
echo ""

# Updates
echo "🔄 6. UPDATING DEPLOYMENT"
echo "   # Backend (Render auto-deploys):"
echo "   git add ."
echo "   git commit -m 'Update'"
echo "   git push"
echo ""
echo "   # Frontend (Vercel auto-deploys):"
echo "   git push"
echo "   # Or manually: vercel --prod"
echo ""

echo "📖 Full guide: See DEPLOY_COMMANDS.md"
echo ""
